### ISSUE TITLE
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu) 

### ISSUE THREAD

**Issue by JiajieLi7012** [bbrument/RNb-NeuS#5]
I got the following error when training the model with the provided preprocessed bearPNG data:

```
Traceback (most recent call last):                                                                          
  File "exp_runner.py", line 480, in <module>                                                               
    runner.train_rnb()                                                                                      
  File "exp_runner.py", line 195, in train_rnb                                                                                                                                                                          
    self.validate_image()                                                                                   
  File "exp_runner.py", line 300, in validate_image                                                         
    lights_dir = self.dataset.light_directions[idv, idl, pixels_y_batch, pixels_x_batch, :].cuda().unsqueeze(0)                                                                                                         
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu) 
```

**Comment by bbrument** [comment]
Hi,
I think that might be a mistake that comes from the Pytorch version. I recently changed it in the "requirements.txt" file.
Now, it's v1.8.0 and I think it solves this issue. Let me know.

**Comment by JiajieLi7012** [comment]
> Hi, I think that might be a mistake that comes from the Pytorch version. I recently changed it in the "requirements.txt" file. Now, it's v1.8.0 and I think it solves this issue. Let me know.

Hi, thanks for your quick reply. When I used the Pytorch of version 1.8.0, I immediately got the following error, which seems an issue with this version of Pytorch according to Google results: 

```
Traceback (most recent call last):
  File "exp_runner.py", line 479, in <module>
    runner = Runner(args.conf, args.mode, args.case, args.is_continue, args.no_albedo)
  File "exp_runner.py", line 33, in __init__
    self.dataset = Dataset(self.conf['dataset'],no_albedo)
  File "/data/lijiaj/RNb-NeuS/models/dataset.py", line 164, in __init__
    self.intrinsics_all_inv = torch.inverse(self.intrinsics_all)  # [n_images, 4, 4]
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)
```

**Comment by JiajieLi7012** [comment]
> Hi, I think that might be a mistake that comes from the Pytorch version. I recently changed it in the "requirements.txt" file. Now, it's v1.8.0 and I think it solves this issue. Let me know.

I solve the problem by downgrading the PyTorch to 1.7.0. Thanks for your quick reply and help again.
